# Employee Data Analysis

## Task 4 - Git, Terminal and Notebook

This notebook analyzes employee data using Pandas.

In [1]:
import pandas as pd

df = pd.read_csv("../data/employees.csv")

df.head()

   id     name department   salary       city
0   1     Arun      Sales  30000.0    Chennai
1   2    Priya         HR      NaN    Chennai
2   3    Rahul         IT  60000.0  Bangalore
3   4    Divya         IT  75000.0    Chennai
4   5  Karthik    Finance  90000.0     Mumbai

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9 non-null      int64
 1   name        9 non-null      str
 2   department  9 non-null      str
 3   salary      7 non-null      float64
 4   city        9 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 492.0 bytes

In [3]:
df.isnull().sum()

id            0
name          0
department    0
salary        2
city          0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(1)

In [5]:
df = df.drop_duplicates()

df.shape

(8, 5)

In [6]:
df["salary"] = df["salary"].fillna(df["salary"].median())

df.isnull().sum()

id            0
name          0
department    0
salary        0
city          0
dtype: int64

In [7]:
df

   id     name department   salary       city
0   1     Arun      Sales  30000.0    Chennai
1   2    Priya         HR  64000.0    Chennai
2   3    Rahul         IT  60000.0  Bangalore
3   4    Divya         IT  75000.0    Chennai
4   5  Karthik    Finance  90000.0     Mumbai
5   6    Meena      Sales  64000.0  Bangalore
6   7   Suresh         IT  68000.0    Chennai
7   8   Anitha         HR  48000.0     Mumbai

In [8]:
df.groupby("department")["salary"].mean()

department
Finance    90000.000000
HR         56000.000000
IT         67666.666667
Sales      47000.000000
Name: salary, dtype: float64

In [9]:
df["department"].value_counts()

department
IT         3
Sales      2
HR         2
Finance    1
Name: count, dtype: int64

In [10]:
df.loc[df["salary"].idxmax()]

id                  5
name          Karthik
department    Finance
salary        90000.0
city           Mumbai
Name: 4, dtype: object

In [11]:
%timeit pd.read_csv("../data/employees.csv")

1.59 ms ± 152 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)